import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Horoscope from "./components/Horoscope"
import Navbar from './components/Navbar'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Horoscopes</title>
        <link rel="icon" href="./horoscope.png" /> 
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta charset="utf-8" />
      </Head>
      <Navbar />
      <Horoscope />
      <video className='videoTag' autoPlay loop muted>
        <source src="https://res.cloudinary.com/dwq30zq8e/video/upload/v1684623101/zodiac_nn9jbh.mp4" type='video/mp4' />

        <main className={`${styles.main}`}>

        </main>
      </video>

    </>
  )
}
